import { AiFillStar } from "react-icons/ai";

const data = [
  {
    id: 1,
    img: "https://m.media-amazon.com/images/I/61b+ACQobxL._AC_UL640_FMwebp_QL65_.jpg",
    title: "Rayon Calf Length Printed Flared Kurti",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "200",
    company: "kurta",
    color: "white",
    category: "sneakers",
  },
  {
    id: 2,
    img: "https://m.media-amazon.com/images/I/61JbJcPZdAL._AC_UL640_FMwebp_QL65_.jpg",
    title: "Rayon Knee Length Printed Straight Kurti",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$150,00",
    newPrice: "200",
    company: "Nike",
    color: "red",
    category: "sneakers",
  },

  {
    id: 3,
    img: "https://m.media-amazon.com/images/I/91Y5tbDXlFL._AC_UL640_FMwebp_QL65_.jpg",
    title: "Polyester Women's Regular A-Line Flared Kurta",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$1100,00",
    newPrice: "200",
    company: "Nike",
    color: "green",
    category: "sneakers",
  },
  {
    id: 4,
    img: "https://m.media-amazon.com/images/I/61kvXNqLkrL._AC_UL640_FMwebp_QL65_.jpg",
    title: "Women Kurta with Pant & Dupatta",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "200",
    company: "Adidas",
    color: "black",
    category: "sneakers",
  },
  {
    id: 5,
    img: "https://m.media-amazon.com/images/I/71mYHZzSPiL._AC_UL640_FMwebp_QL65_.jpg",
    title: "Silver Plated Alloy Necklace Set with Earrings",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "200",
    company: "Vans",
    color: "green",
    category: "flats",
  },
  {
    id: 6,
    img: "https://m.media-amazon.com/images/I/51HTyfRbS9L._AC_UL640_FMwebp_QL65_.jpg",
    title: "Italian Designer Platinum Plated",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "50",
    company: "Adidas",
    color: "black",
    category: "flats",
  },

  {
    id: 7,
    img: "https://m.media-amazon.com/images/I/71U09q0qqZL._AC_UL640_FMwebp_QL65_.jpg",
    title: "RAS Luxury Oils Flaunt Pigmentation & Complexion Correcting Serum",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "50",
    company: "Vans",
    color: "white",
    category: "flats",
  },

  {
    id: 8,
    img: "https://m.media-amazon.com/images/I/51jBGx07u1L._AC_UL640_FMwebp_QL65_.jpg",
    title: "LAKMÉ Lip Love Spf 15 Lip Balm For Soft, Smooth, And Moisturised Lips",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "200",
    company: "Nike",
    color: "green",
    category: "sneakers",
  },

  {
    id: 9,
    img: "https://m.media-amazon.com/images/I/61-cBsLhJHL._AC_UY695_.jpg",
    title: "Adidas Men's Sneaker",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "200",
    company: "Adidas",
    color: "blue",
    category: "sneakers",
  },

  {
    id: 10,
    img: "https://m.media-amazon.com/images/I/51X0Mo7f5HL._AC_UL640_FMwebp_QL65_.jpg",
    title: "PROTOUCH Complete Hair Growth Combo",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "150",
    company: "Puma",
    color: "green",
    category: "sneakers",
  },
  {
    id: 11,
    img: "https://m.media-amazon.com/images/I/61giO5ifVzL._AC_UL640_FMwebp_QL65_.jpg",
    title: "RENEE Bold 4-4-in-1 Kajal",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "150",
    company: "Puma",
    color: "red",
    category: "sneakers",
  },
  {
    id: 12,
    img: "https://m.media-amazon.com/images/I/61Yf6Gbl-fL._AC_UL640_FMwebp_QL65_.jpg",
    title: "YouBella Jewellery Sets for Women Pearl Studded Choker Necklace",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "150",
    company: "Puma",
    color: "black",
    category: "sneakers",
  },
  {
    id: 13,
    img: "https://m.media-amazon.com/images/I/71iOoLgCrEL._AC_UL640_FMwebp_QL65_.jpg",
    title: "Turquoise Blue & Green Meenakari",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "150",
    company: "Puma",
    color: "white",
    category: "sneakers",
  },
  {
    id: 14,
    img: "https://m.media-amazon.com/images/I/71w8bbKVX-L._AC_UL640_FMwebp_QL65_.jpg",
    title: "Green Stones & Dazzling Austrian Diamonds",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "150",
    company: "Puma",
    color: "black",
    category: "sneakers",
  },

  {
    id: 15,
    img: "https://m.media-amazon.com/images/I/61SG-u7I0zL._AC_UL640_FMwebp_QL65_.jpg",
    title: "Latest Stylish Rose Gold Tulip Design Earrings Necklace",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "100",
    company: "Puma",
    color: "green",
    category: "sneakers",
  },
  {
    id: 16,
    img: "https://m.media-amazon.com/images/I/51XMTbnoWiL._AC_UL640_FMwebp_QL65_.jpg",
    title: "Mamaearth Onion Shampoo for Anti Hair Fall & Hair Growth",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "100",
    company: "Vans",
    color: "red",
    category: "flats",
  },
  {
    id: 17,
    img: "https://m.media-amazon.com/images/I/41u7lc-7f+L._AC_UL640_FMwebp_QL65_.jpg",
    title: "Biotique Green Apple Shine & Gloss Shampoo",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "100",
    company: "Vans",
    color: "white",
    category: "sandals",
  },
  {
    id: 18,
    img: "https://m.media-amazon.com/images/I/71EWqA3punL._AC_UL640_FMwebp_QL65_.jpg",
    title: "Park Avenue Beer shampoo for Shiny & Bouncy Hair",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "100",
    company: "Vans",
    color: "blue",
    category: "sandals",
  },
  {
    id: 19,
    img: "https://m.media-amazon.com/images/I/51QnCyfceaL._AC._SR360,460.jpg",
    title: "L'OREAL PROFESSIONNEL PARIS Absolut Repair Shampoo",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "50",
    company: "Nike",
    color: "black",
    category: "sandals",
  },
  {
    id: 20,
    img: "https://m.media-amazon.com/images/I/61bncQ44yML._AC_UX695_.jpg",
    title: "Chunky High Heel",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "50",
    company: "Vans",
    color: "black",
    category: "heels",
  },
];

export default data;